### PR TITLE
#6 fix

### PR DESCRIPTION
**Pull request by JWPapi**
Just made the redirect section optional and handleable by a parameter and added it to readme.

However I had some problems with formatting. The format looks nice on me locally but not on github. This is my first pull request, so glad for help.

### CODE REVIEW

**Comment by helgatheviking** [comment]
Hi Julian! Thanks so much for this... it looks pretty solid. Question, should the attribute be named `redirect_to_cart` ? Technically you can filter Woo to redirect anywhere and conditionally depending on what is added. What if we called it `allow_redirect`? And it was true by default? then `allow_redirect="false"` when you want to cancel redirects. I guess it could also be called `suppress_redirect` and be `false` by default. What do you think? 

Otherwise, there are some code standards things.. but you were probably just mimicking my dodgy code standards :) So I will need to clean those up after merging. (yoda conditions, spaces after `if`, and strict `===` jump out immediately).

**Comment by JWPapi** [comment]
I’m fine with `allow_redirect` . When I’m just pushing to my fork it will be automatically included in the pull request, correct?

I’ll also change the code standard things. It’s been my first pull request :)

**Comment by helgatheviking** [comment]
Yes, as you push more commits to your `JWPapi:master` branch the pull request should update automatically. :)

**Comment by helgatheviking** [comment]
@JWPapi Ok, I'm a little confused now.

Your PR has changed from filtering `woocommerce_add_to_cart_form_action` to filtering `woocommerce_add_to_cart_redirect` which is not the same thing. In fact, when filtering `woocommerce_add_to_cart_redirect` I can't turn any callbacks attached to that off since the redirect handling all happens on page load and would be entirely unaware of the shortcode attributes.

Filtering `woocommerce_add_to_cart_form_action` prevents us from redirecting to the single product's page where the "added to cart" notice shows. it does this by nuking the [ `<form action="">` parameter](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/add-to-cart/simple.php#L32). 

I was assuming that folks would want to stay on the same page as it would be confusing to redirect to a different page showing the same product. However, you can still redirect to the cart/checkout if you are filtering `woocommerce_add_to_cart_redirect`.

Here's an example snippet to test with:

```
function kia_redirect_to_checkout() {
	return wc_get_checkout_url();
}
add_filter( 'woocommerce_add_to_cart_redirect', 'kia_redirect_to_checkout' );
```

So, can you take me back to the beginning here... what are you trying to achieve that is not currently possible?

**Comment by JWPapi** [comment]
Good Morning @helgatheviking I’m sorry that was not a conscious choice, but rather a autofill change. I’ve changed it back and I should take care that doesn’t happen again.

**Comment by helgatheviking** [comment]
closed in favor of #10 . thank you @JWPapi for your help and suggestions.

**Pull request closed without merging**
